server:
  port: 18080

spring:
  datasource:
    rw:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/tx_rw
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    ro:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/tx_ro
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: none
    generate-ddl: true

#  sql:
#    init:
#      schema-locations: classpath:/schema.sql



logging.level:
  org.springframework.batch: DEBUG
  org.hibernate.SQL: debug



