server:
  port: 18080

spring:
  datasource:
    rw:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/test
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
    ro:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3307/test_slave
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

#  sql:
#    init:
#      schema-locations: classpath:/schema.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      show_sql: true
      ddl-auto: none
    generate-ddl: true

logging.level:
  org.springframework.batch: DEBUG
  org.hibernate.SQL: debug



